# StatSeed verification: R-side calculations
# Reads the same CSVs generated by data_gen.py and computes equivalent statistics.

library(jsonlite)

DATA <- file.path(getwd(), "data")
results <- list()

# 1. Welch's t-test
df <- read.csv(file.path(DATA, "two_groups.csv"))
a <- df$value[df$group == "A"]
b <- df$value[df$group == "B"]
t1 <- t.test(a, b, var.equal = FALSE)
results$welch_t <- list(statistic = unname(t1$statistic), p_value = t1$p.value)

# 2. Paired t-test (StatSeed: stats.ttest_rel(before, after) where before=pre, after=post)
dfp <- read.csv(file.path(DATA, "paired.csv"))
t2 <- t.test(dfp$pre, dfp$post, paired = TRUE)
results$paired_t <- list(statistic = unname(t2$statistic), p_value = t2$p.value)

# 3. Mann-Whitney U (Wilcoxon rank-sum)
w1 <- wilcox.test(a, b, exact = FALSE, correct = FALSE)
results$mannwhitney_u <- list(statistic = unname(w1$statistic), p_value = w1$p.value)

# 4. Wilcoxon signed-rank (StatSeed: stats.wilcoxon(before, after) where before=pre, after=post)
w2 <- wilcox.test(dfp$pre, dfp$post, paired = TRUE, exact = FALSE, correct = FALSE)
results$wilcoxon <- list(statistic = unname(w2$statistic), p_value = w2$p.value)

# 5. Chi-square test of independence
chisq_df <- read.csv(file.path(DATA, "chisq_table.csv"), row.names = 1)
c1 <- chisq.test(as.matrix(chisq_df), correct = FALSE)
results$chi_square <- list(statistic = unname(c1$statistic), p_value = c1$p.value, dof = unname(c1$parameter))

# 6. Fisher's exact test
fisher_df <- read.csv(file.path(DATA, "fisher_table.csv"), row.names = 1)
f1 <- fisher.test(as.matrix(fisher_df))
results$fisher_exact <- list(statistic = unname(f1$estimate), p_value = f1$p.value)

# 7,8. Pearson / Spearman correlation
corr_df <- read.csv(file.path(DATA, "correlation.csv"))
p1 <- cor.test(corr_df$x, corr_df$y, method = "pearson")
results$pearson <- list(statistic = unname(p1$estimate), p_value = p1$p.value)
s1 <- cor.test(corr_df$x, corr_df$y, method = "spearman")
results$spearman <- list(statistic = unname(s1$estimate), p_value = s1$p.value)

# 9. One-way ANOVA
anova_df <- read.csv(file.path(DATA, "anova.csv"))
anova_df$group <- as.factor(anova_df$group)
fit <- aov(value ~ group, data = anova_df)
a_summary <- summary(fit)[[1]]
results$anova <- list(statistic = a_summary["group", "F value"], p_value = a_summary["group", "Pr(>F)"])

# 10. Multiple regression
reg_df <- read.csv(file.path(DATA, "regression.csv"))
lm_fit <- lm(y ~ x1 + x2 + x3, data = reg_df)
s <- summary(lm_fit)
fstat <- s$fstatistic
f_p <- pf(fstat["value"], fstat["numdf"], fstat["dendf"], lower.tail = FALSE)
results$regression <- list(
  f_statistic = unname(fstat["value"]),
  f_p_value = unname(f_p),
  r_squared = s$r.squared,
  coefficients = as.list(coef(lm_fit)),
  coef_p_values = as.list(s$coefficients[, "Pr(>|t|)"])
)

out_path <- file.path(dirname(DATA), "r_results.json")
write(toJSON(results, auto_unbox = TRUE, pretty = TRUE, digits = 15), out_path)
cat("Wrote", out_path, "\n")
cat(toJSON(results, auto_unbox = TRUE, pretty = TRUE, digits = 15))
